spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    password: Contrasena_123
    url: jdbc:oracle:thin:@adb.mx-queretaro-1.oraclecloud.com:1522/g96e4d799cd2684_eq5chatbotwu5ru_tp.adb.oraclecloud.com?TNS_ADMIN=/oci-react-samples-springboot-bot/MtdrSpring/wallet
    username: TODOUSER
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${ui_username}
      password: ${ui_password}
